connector:
  subscriptionId: "esdb-elastic-connector"
source:
  connectionString: "esdb://esdb:2113?tls=false"
  concurrencyLimit: 10
target:
  connectionString: "http://es01:9200"
  dataStream:
    indexName: "eventlog"
    template:
      templateName: "eventlog-template"
    lifecycle:
      policyName: "eventlog-policy"
      tiers:
        - tier: "hot"
          minAge: "1d"
          priority: 100
          rollover:
            maxAge: "1d"
            maxSize: "100mb"
        - tier: "warm"
          minAge: "1d"
          priority: 50
          forceMerge:
            maxNumSegments: 1
        - tier: "cold"
          minAge: "1d"
          priority: 0
          readOnly: true