connector:
  connectorId: "esdb-mongo-connector"
  connectorAssembly: "Eventuous.Connector.Mongo"
  diagnostics:
    tracing:
      enabled: true
      exporters: [zipkin]
    metrics:
      enabled: true
      exporters: [prometheus]
    traceSamplerProbability: 0
source:
  connectionString: "esdb://localhost:2113?tls=false"
  concurrencyLimit: 1
target:
  connectionString: "mongodb://mongoadmin:secret@localhost:27017"
  collection: bookings
grpc:
  uri: "http://localhost:9091"