version: '3.7'

services:
  mongo:
    container_name: eventuous-connector-mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

networks:
  eventuous-connector-mongo:
    driver: bridge