connector:
  connectorId: "esdb-elastic-connector"
  connectorAssembly: "Eventuous.Connector.EsdbElastic"
  diagnostics:
    tracing:
      enabled: true
      exporters: [zipkin]
    metrics:
      enabled: true
      exporters: [prometheus]
    traceSamplerProbability: 0
source:
  connectionString: "esdb://localhost:2113?tls=false"
  concurrencyLimit: 1
target:
  connectionString: "http://localhost:9200"
  connectorMode: "produce"
  dataStream:
    indexName: "eventlog"
    template:
      templateName: "eventlog-template"
    lifecycle:
      policyName: "eventlog-policy"
      tiers:
        - tier: "hot"
          minAge: "1d"
          priority: 100
          rollover:
            maxAge: "1d"
            maxSize: "100mb"
        - tier: "warm"
          minAge: "1d"
          priority: 50
          forceMerge:
            maxNumSegments: 1
        - tier: "cold"
          minAge: "1d"
          priority: 0
          readOnly: true