apiVersion: v1
kind: Service
metadata:
  annotations:
{{- if and .Values.prometheus.metrics (not .Values.prometheus.operator) }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
{{- end }}
  name: {{ template "connector.fullname" . }}
  labels:
    app: {{ template "connector.name" . }}
    chart: {{ template "connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: {{ .Values.tier }}
spec:
  ports:
  - name: web
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ template "connector.name" . }}
    release: {{ .Release.Name }}
    tier: {{ .Values.tier }}
  type: ClusterIP
