version: '3.7'

services:
  sqlserver:
    container_name: eventuous-connector-sqlserver
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

networks:
  eventuous-connector-sql:
    driver: bridge