name: "Build and push Docker"

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
    paths-ignore:
      - '**.md'
      - '**.yaml'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Docker
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.100-preview.4.23260.5'
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Create and push Docker container
        run: |
          dotnet publish --runtime linux-x64 -p:PublishProfile=DefaultContainer -c Release --self-contained
          dotnet publish --runtime linux-arm64 -p:PublishProfile=DefaultContainer -c Release --self-contained
