name: Publish Preview NuGet

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yaml'
      - docs/**

jobs:
  nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Create and push NuGet package
        run: |
          dotnet pack -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet nuget push nuget/**/*.nupkg --skip-duplicate --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/eventuous/api/v2/package
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
